/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bbb.ui;

import com.bbb.utils.TrayIconUtils;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import org.apache.log4j.Logger;

/**
 *
 * @author Totaram
 */
/**
 * MainAppFrame CLASS THIS IS MAIN FRAME HOLD ALL PANEL
 */
public class MainAppFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainAppFrame
     */
    final static Logger logger = Logger.getLogger(MainAppFrame.class);
    public static TrayIcon trayIcon = null;
    public static ProgressBarDia progressDialog = null;
    public ProcessingIcon processingPanel = null;
    public SyncPanel syncPanel = null;
    public static RestoreDia restoreDia = null;

    /**
     * MainAppFrame CONSTRUCTOR SET CARD LAYOUT
     */
    public MainAppFrame() {
        initComponents();
        this.setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((dim.width - this.getWidth()) / 2, (dim.height - this.getHeight()) / 2);
        setIconImage(TrayIconUtils.appIcon);
        LoginPanel loginPanel = new LoginPanel(this);
        processingPanel = new ProcessingIcon(this);
        syncPanel = new SyncPanel(this);
        CardLayout card = new CardLayout();
        getContentPane().setLayout(card);
        getContentPane().add(loginPanel, "loginPanel");
        getContentPane().add(processingPanel, "processingPanel");
        getContentPane().add(syncPanel, "syncPanel");
        progressDialog = new ProgressBarDia(this, true);
        restoreDia = new RestoreDia(this, true);
        restoreDia.setVisible(false);

    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("bbbappversion"); // NOI18N
        setTitle(bundle.getString("bbb.app.version")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
